version: '3.7'

services:

  mongo:
    image: mongo:3.6.20-xenial
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017
